spring:
  application:
    name: gulimall-coupon
  datasource:
    username: admin
    password: Admin@2024
    url: jdbc:mysql://117.72.167.140:3306/gulimall_sms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 117.72.167.140:8848
      password: Zkyy2021
      username: nacos

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 7001
